name: builder
on:
    push:
        branches:
            - main
jobs:
    buildx:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build the images
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: edzhu/cargo-edit:latest
                load: true
            - name: Test the image
              run: |
                docker run --rm edzhu/cargo-edit:latest cargo set-version -V
            - name: Push the images
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                platforms: linux/amd64,linux/arm64
                tags: edzhu/cargo-edit:latest
              